# Generated by Django 5.0.4 on 2024-11-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0025_datamodeloutput_num_plants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='test',
        ),
    ]
