# Generated by Django 5.0.4 on 2024-11-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapp', '0027_remove_plant_h_max_remove_plant_column_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='n',
            field=models.FloatField(),
        ),
    ]
